PL-1018 add types to BuildResponse
BenchLabs/gojenkins pull request #3
Opened 2018-02-15 01:45 UTC by philwhln

2018-02-15 03:58 UTC, trevoro commented on build.go
> +type RFC1123Timestamp time.Time
👏

2018-02-15 17:37 UTC, j-martin requested changes
Please add:
```
		EnclosingBlockNames []string    `json:"enclosingBlockNames"`
		EnclosingBlocks     []string    `json:"enclosingBlocks"`
```

2018-02-15 17:37 UTC, j-martin commented on build.go
> +		Timestamp RFC1123Timestamp `json:"timestamp"`
https://jenkins.in.bench.co/view/Masters/job/BenchLabs/job/eventing-service/job/master/232/testReport/api/json

You also want:

```
		EnclosingBlockNames []string    `json:"enclosingBlockNames"`
		EnclosingBlocks     []string    `json:"enclosingBlocks"`
```

```
type AutoGenerated struct {
	Class       string        `json:"_class"`
	TestActions []interface{} `json:"testActions"`
	Duration    float64       `json:"duration"`
	Empty       bool          `json:"empty"`
	FailCount   int           `json:"failCount"`
	PassCount   int           `json:"passCount"`
	SkipCount   int           `json:"skipCount"`
	Suites      []struct {
		Cases []struct {
			TestActions     []interface{} `json:"testActions"`
			Age             int           `json:"age"`
			ClassName       string        `json:"className"`
			Duration        float64       `json:"duration"`
			ErrorDetails    interface{}   `json:"errorDetails"`
			ErrorStackTrace interface{}   `json:"errorStackTrace"`
			FailedSince     int           `json:"failedSince"`
			Name            string        `json:"name"`
			Skipped         bool          `json:"skipped"`
			SkippedMessage  interface{}   `json:"skippedMessage"`
			Status          string        `json:"status"`
			Stderr          string        `json:"stderr"`
			Stdout          string        `json:"stdout"`
		} `json:"cases"`
		Duration            float64     `json:"duration"`
		EnclosingBlockNames []string    `json:"enclosingBlockNames"`
		EnclosingBlocks     []string    `json:"enclosingBlocks"`
		ID                  string      `json:"id"`
		Name                string      `json:"name"`
		NodeID              string      `json:"nodeId"`
		Stderr              string      `json:"stderr"`
		Stdout              string      `json:"stdout"`
		Timestamp           interface{} `json:"timestamp"`
	} `json:"suites"`
}
```

2018-02-16 17:36 UTC, j-martin approved these changes

2018-02-16 17:40 UTC, merged